project_id = "mcvxcleslvgntufnrqds"

[functions.refresh-kpis]
verify_jwt = false

[functions.ai-categorize]
verify_jwt = false

[functions.webhook-plaid]
verify_jwt = false

[functions.import-csv]
verify_jwt = false

[functions.sync-qbo]
verify_jwt = false

[db]
major_version = 15
